### PR TITLE
Cleanup grammar and actions // Remove unnecessary fstring code

### PR DESCRIPTION
**Pull request by lysnikolaou**

### CODE REVIEW

**Comment by lysnikolaou** [comment]
cc @pablogsal @isidentical

**Review by isidentical — APPROVED** [review]
Super cool, love the minus 2566 lines removed (bye bye string parser) 😄

**Review by pablogsal — APPROVED** [review]
Oh yesssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

**Comment by pablogsal** [comment]
Man this makes me so happy ❤️

**Comment by lysnikolaou** [comment]
Oh it made me really happy as well, as I was working on it.

**Comment by sunmy2019** [comment]
Hello,

you have changed the return type of `_PyPegen_parse_string` to `PyObject*`, but you didn't change every return clause.
some cluase will return `-1`. A new PR should be made to correct these.


https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L180-L263

https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L217
https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L224
https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L229
https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L240
https://github.com/pablogsal/cpython/blob/7b9b97325806c8adbc5d91d130663973c80e601a/Parser/string_parser.c#L254

**Comment by lysnikolaou** [comment]
Good catch @sunmy2019! Thanks a lot!

**Pull request merged**
